# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce5017a5727c96f529993324642ef724b197f127c0e9a86e0f46a896ad5bf34729d6e9a4fa355fd24f502532a0613c201f417d0f5b56b13b4b52340dd45bc09

test:
  secret_key_base: 5d8169ff443bc5e68fad170d4c990d4db998249efa97479497bca3291a63c374f7c5a900331e6f20d9324542122501ac684df49e21e5b1f62d3cccef897a75ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
